# Generated by Django 3.1 on 2020-08-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price_deal',
            fields=[
                ('market', models.CharField(max_length=20)),
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='webnovel',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('detaild_link', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='webtoon',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('detaild_link', models.CharField(max_length=1000)),
                ('images', models.CharField(max_length=50000)),
            ],
        ),
    ]
